apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-core.fullname" . }}
  labels:
    {{- include "auth-core.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "auth-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auth-core.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "auth-core.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          env:
            - name: PORT
              value: {{ .Values.image.port }}
            - name: CORS_ORIGIN
              value: {{ .Values.cors.origin | quote }}
            - name: COOKIE_DOMAIN
              value: {{ .Values.cookie.domain | quote }}
            - name: COOKIE_SECRET
              value: {{ .Values.cookie.secret | quote }}
            - name: SESSION_NAME
              value: {{ .Values.session.name | quote }}
            - name: SESSION_TIMEOUT
              value: {{ .Values.session.timeout | quote }}
            - name: AUTO_MAILER_URL
              value: {{ .Values.auto_mailer.url | quote }}
            - name: VERIFY_EMAIL_URL
              value: {{ .Values.auto_mailer.verify_email_url | quote }}
            - name: DATABASE_URL
              value: {{ include "auth-core.database.url" . | quote }}
            - name: SESSION_STORAGE_URL
              value: {{ include "auth-core.redis.url" . | quote }}
            - name: JWT_PUBLIC_ACCESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.jwt.access.secretName" . }}
                  key: public
            - name: JWT_PRIVATE_ACCESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.jwt.access.secretName" . }}
                  key: private
            - name: JWT_EXPIRES_IN_ACCESS
              value: {{ .Values.jwt.access.expires_in | quote }}
            - name: JWT_PUBLIC_REFRESH
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.jwt.refresh.secretName" . }}
                  key: public
            - name: JWT_PRIVATE_REFRESH
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.jwt.refresh.secretName" . }}
                  key: private
            - name: JWT_EXPIRES_IN_REFRESH
              value: {{ .Values.jwt.refresh.expires_in | quote }}
            - name: JWT_PUBLIC_EMAIL_VERIFICATION
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.jwt.email_verification.secretName" . }}
                  key: public
            - name: JWT_PRIVATE_EMAIL_VERIFICATION
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.jwt.email_verification.secretName" . }}
                  key: private
            - name: JWT_EXPIRES_IN_EMAIL_VERIFICATION
              value: {{ .Values.jwt.email_verification.expires_in | quote }}

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
