apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-core.fullname" . }}
  labels:
    {{- include "auth-core.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "auth-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auth-core.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "auth-core.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: prisma-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.database.secretName" . }}
                  key: url
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          envFrom:
            - configMapRef:
                name: {{ include "auth-core.configName" . }}
          env:
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.cookie.secretName" . }}
                  key: secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.database.secretName" . }}
                  key: url
            - name: SESSION_STORAGE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.session_storage.secretName" . }}
                  key: url
            - name: JWT_PUBLIC_ACCESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.jwt.access.secretName" . }}
                  key: public
            - name: JWT_PRIVATE_ACCESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.jwt.access.secretName" . }}
                  key: private
            - name: JWT_PUBLIC_REFRESH
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.jwt.refresh.secretName" . }}
                  key: public
            - name: JWT_PRIVATE_REFRESH
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.jwt.refresh.secretName" . }}
                  key: private
            - name: JWT_PUBLIC_EMAIL_VERIFICATION
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.jwt.email_verification.secretName" . }}
                  key: public
            - name: JWT_PRIVATE_EMAIL_VERIFICATION
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-core.jwt.email_verification.secretName" . }}
                  key: private

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
